
spring:
  datasource:
    name: property  #数据库名
    url: jdbc:mysql://localhost:3306/property #url
    username: root  #用户名
    password: 19950519zzz  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

  mybatis:
    mapper-locations: classpath:mapper/*.xml  #配置映射文件
    type-aliases-package: com.zln.bookkeeping.bean
